feat(commands): add third subtype support in subtype conversion command
corowne/lorekeeper pull request #1048
Opened 2024-09-02 23:43 UTC by SpeedyD

Based on #1047 that coincidentally passed just minutes ago!

- make _third_ subtype support work out of the box

That's all!

2024-09-02 23:44 UTC, itinerare commented
Wow! I would have never expected this very PR!

2024-09-02 23:48 UTC, itinerare requested changes
Just the one significant note... otherwise looks good!

2024-09-02 23:48 UTC, itinerare commented on app/Console/Commands/ConvertCharacterSubtype.php
> +                $thirdSubtype = false;
This should be set above alongside `$secondSubtype`  (or similar) so that it's always set and doesn't cause errors from it... not being set...

2024-09-02 23:48 UTC, itinerare commented on app/Console/Commands/ConvertCharacterSubtype.php
> +                if (Schema::hasColumn('character_images', 'subtype_id_3') && Schema::hasColumn('design_updates', 'subtype_id_3')) {
Is it safe to assume that these columns will only be present if the second subtype ones are? I assume yes, but...

2024-09-02 23:49 UTC, SpeedyD commented on app/Console/Commands/ConvertCharacterSubtype.php
> +                $thirdSubtype = false;
D'oh! See, I started with this part, and I thought later "oh yeah, I should fix that one part in the beginning"...

..and then forgot. Lemme fix that quick.

2024-09-02 23:51 UTC, SpeedyD commented on app/Console/Commands/ConvertCharacterSubtype.php
> +                if (Schema::hasColumn('character_images', 'subtype_id_3') && Schema::hasColumn('design_updates', 'subtype_id_3')) {
Third Subtype is DIRECTLY built off of Second Subtype. It's literally your code + mine.

So if SecondSubtype columns are missing, the error lies with the site tech, not the code.

2024-09-02 23:52 UTC, itinerare commented on app/Console/Commands/ConvertCharacterSubtype.php
> +                if (Schema::hasColumn('character_images', 'subtype_id_3') && Schema::hasColumn('design_updates', 'subtype_id_3')) {
I figured, but wanted to double-check, just in case |D

2024-09-02 23:53 UTC, itinerare approved these changes

2024-09-03 06:38 UTC, ScuffedNewt approved these changes

2024-09-03 11:02 UTC, merged