hotfix: Fix visibility issues for gallery submissions
corowne/lorekeeper pull request #1082
Opened 2024-10-07 15:11 UTC by preimpression

Regarding vulnerability I mentioned on Discord.

2024-10-07 15:38 UTC, itinerare requested changes

2024-10-07 15:38 UTC, itinerare commented on app/Models/User/User.php
> +        return $this->hasMany('App\Models\Gallery\GallerySubmission')->where('user_id', $this->id)->orWhereIn('id', GalleryCollaborator::where('user_id', $this->id)->where('type', 'Collab')->pluck('g
Didn't realize this was in the user model... the `visible()` scope should probably be moved to the relevant controller (and the `accepted()` scope removed)

2024-10-07 16:43 UTC, preimpression commented on app/Models/User/User.php
> +        return $this->hasMany('App\Models\Gallery\GallerySubmission')->where('user_id', $this->id)->orWhereIn('id', GalleryCollaborator::where('user_id', $this->id)->where('type', 'Collab')->pluck('g
OH word true, one sec

2024-10-07 16:47 UTC, itinerare approved these changes

2024-10-08 15:12 UTC, SpeedyD approved these changes

2024-10-08 15:29 UTC, itinerare commented
Holding for merge/release later this week.

2024-10-27 13:05 UTC, merged