fix criteria for ItemRarity and ItemCategoryRarity loot tables
corowne/lorekeeper pull request #1124
Opened 2024-11-11 22:43 UTC by rattusquo

updated rarity-based loot tables to pass '=' criteria as '==' to resolve an error in evaluating sort order. thank you to Newt for pointing out this fix :) please note that any existing loot tables with this criteria will need to be updated in the admin panel, as this fix resets their criteria field.

2024-11-11 23:07 UTC, ScuffedNewt commented
ideally this would be retroactive but what can you do!

2024-11-11 23:07 UTC, ScuffedNewt approved these changes

2024-11-11 23:41 UTC, itinerare commented
For my part, I'd definitely ask for this either to not break existing tables or for existing tables to be handled via some means (conversion command, etc.); it's a must one way or another.

2025-01-05 01:03 UTC, SpeedyD approved these changes
I thought I approved this MONTHS ago O_o

2025-01-08 15:09 UTC, itinerare requested changes
Formalizing my earlier comment as a review ~~mostly so the PR is flagged appropriately and I don't keep wandering in here having forgotten what's up~~...
> For my part, I'd definitely ask for this either to not break existing tables or for existing tables to be handled via some means (conversion command, etc.); it's a must one way or another.

2025-01-12 18:14 UTC, itinerare commented
Closed due to inactivty/in favor of #1191.

2025-01-12 18:14 UTC, closed without merging