item rarity searches
corowne/lorekeeper pull request #1125
Opened 2024-11-11 23:37 UTC by rattusquo

added dropdowns for item rarity filtering to various areas of the site. search dropdown is contained within the config check for item entry expansion's extra fields alongside artist, since item rarity only applies when that portion of the ext is enabled :)

2024-11-11 23:45 UTC, itinerare approved these changes

2024-11-12 09:21 UTC, SpeedyD commented
I like this, I in fact spoke with Newt the other day that we should add this, haha..

I just have ONE question: Could you also add a "No Rarity" option? If not, I can do that later, no worries. But since Item Rarity is _optional_, it'd be nice for folk to be able to get results that specifically don't have a rarity. :)

2024-11-12 14:43 UTC, rattusquo commented
good call, should be updated now :)

2024-11-12 15:18 UTC, itinerare approved these changes

2024-11-12 15:22 UTC, ScuffedNewt requested changes

2024-11-12 15:22 UTC, ScuffedNewt commented on app/Http/Controllers/Admin/Data/ItemController.php
> +            'rarities'   => ['none' => 'Any Rarity'] + ['no_rarity' => 'No Rarity'] + Rarity::orderBy('rarities.sort', 'DESC')->pluck('name', 'id')->toArray(),
instead of having `['none' => 'Any Rarity']` please instead use a `placeholder` on the form

2024-11-12 15:22 UTC, ScuffedNewt commented on app/Http/Controllers/Admin/Data/ItemController.php
> +        if (isset($data['rarity_id']) && $data['rarity_id'] != 'none') {
using placeholder means you do not have to check `!= none`

2024-11-12 15:22 UTC, ScuffedNewt commented on resources/views/character/inventory.blade.php
> +                    {!! Form::select('rarity_id', $rarities, Request::get('rarity_id'), ['class' => 'form-control']) !!}
`['class' => 'form-control', 'placeholder' => 'Any Rarity']`

2024-11-12 17:20 UTC, rattusquo commented
done, thanks Newt! also brought artist/category selections in line with this change where relevant.

2024-11-12 18:01 UTC, ScuffedNewt approved these changes
Awesome!! thank you!

2024-11-12 18:11 UTC, itinerare commented on app/Http/Controllers/Users/InventoryController.php
>              'artists'     => ['none' => 'Any Artist'] + User::whereIn('id', Item::whereNotNull('artist_id')->pluck('artist_id')->toArray())->pluck('name', 'id')->toArray(),
This pseudo-placeholder probably should be taken out...

2024-11-12 18:21 UTC, rattusquo commented on app/Http/Controllers/Users/InventoryController.php
>              'artists'     => ['none' => 'Any Artist'] + User::whereIn('id', Item::whereNotNull('artist_id')->pluck('artist_id')->toArray())->pluck('name', 'id')->toArray(),
missed that one, whoops

2024-11-12 18:56 UTC, itinerare approved these changes

2024-11-12 18:57 UTC, merged

2024-11-13 22:19 UTC, SpeedyD commented
It's already merged in, but I still wanted to say I heavily approve of this, and I thank you for taking the time to do this, @rattusquo! :)