feat: Extension/admin logs (also merging of latest release/release-2.0.0)
corowne/lorekeeper pull request #135
Opened 2021-07-23 00:05 UTC by Ne-wt

discussed on disc, the ONLY thing i can think of potentially being an issue is $user not being defined in an area i may have missed though I tried my best to test everywhere I added it. May also be some spots that should have logging that I've neglected

2021-07-23 00:05 UTC, Ne-wt commented
just remembered I need to add user edit logs - will add asap so this is just a draft as a ''don't forget newt''

2021-07-23 18:51 UTC, preimpression requested changes
Pretty much all just proofreading for typos! I checked Google on them to see if they were just Europe vs US but that didn't seem to be the case.

2021-07-23 18:51 UTC, preimpression commented on app/Http/Controllers/Admin/Users/UserController.php
> +            if(!logAdminAction($staff, 'Editted User', 'Editted '.$user->displayname)) { flash('Failed to log admin action.')->error(); return redirect()->back();}
Typos in this file
Editted -> Edited

2021-07-23 18:51 UTC, preimpression commented on app/Services/CharacterCategoryService.php
> +            if(!logAdminAction($user, 'Editted Character Category', 'Editted '.$category->displayName)) throw new \Exception("Failed to log admin action.");
Editted -> Edited

2021-07-23 18:51 UTC, preimpression commented on app/Services/CurrencyManager.php
> +                    if(!logAdminAction($staff, 'Currency Debit', 'Debitted '.$data['quantity'].' '.$currency->displayName.' from '.$user->displayname)) throw new \Exception("Failed to log admin actio
Debitted -> Debited

2021-07-23 18:51 UTC, preimpression commented on app/Services/CurrencyService.php
> +            // if(DB::table('currencys')->where('data->resell', $currency->id)->exists()) throw new \Exception("An currency currently uses this currency for its resale value. Please change the resale
I don't think this was meant to be changed?

2021-07-23 18:51 UTC, preimpression commented on app/Services/GalleryManager.php
> +            if($user->isStaff) if(!logAdminAction($user, 'Editted Gallery Submission', 'Editted gallery submission '.$submission->displayName)) throw new \Exception("Failed to log admin action.");
Editted -> Edited

2021-07-23 18:51 UTC, preimpression commented on app/Services/ItemService.php
> +            if(!logAdminAction($user, 'Editted Item Tag', 'Editted '.$tag.' tag on '.$item->displayName)) throw new \Exception("Failed to log admin action.");
Editted -> Edited

2021-09-02 18:21 UTC, Draginraptor reviewed
I'd been waiting for the typo fixes Uri had pointed out, but I otherwise think that the code looks fine?

2021-09-02 21:04 UTC, Ne-wt commented
lol i forgot to fix those honestly, will get to it asap

2021-09-03 07:06 UTC, Draginraptor approved these changes

2021-09-04 19:41 UTC, preimpression approved these changes

2021-09-04 19:44 UTC, merged