Extension/deactivate account
corowne/lorekeeper pull request #296
Opened 2022-04-06 22:51 UTC by preimpression

Ability to deactivate account
I think there was one little conflict that I can fix up

2022-04-06 22:52 UTC, preimpression commented
"one conflict"  = 11 conflicts apparently

2022-04-06 23:39 UTC, itinerare commented
I'm marking this as draft-- feel free to pop it out of draft status once the conflicts are resolved!

2022-05-05 00:24 UTC, preimpression commented
Fixed conflicts! Will note though that the workflow file will need to be re-added since I can't push to github with it, despite having the workflows permissions

2022-05-15 17:28 UTC, itinerare requested changes

2022-05-15 17:28 UTC, itinerare commented on app/Http/Controllers/Users/AccountController.php
> +            flash('You have successfully successfully.')->success();
Check this message...

2022-05-15 17:28 UTC, itinerare commented on app/Services/UserService.php
> +=======
Unresolved conflict?

2022-05-15 17:28 UTC, itinerare commented on app/Services/UserService.php
> +                    $galleryManager->postStaffComments($submission->id, ['staff_comments' => 'User\'s account was deactivated.'], ($staff ? $staff : $user));
Gallery staff comments are defunct in favor of comments-comments... I should clean that up though

2022-05-15 17:28 UTC, itinerare commented on resources/views/account/_deactivate_confirmation.blade.php
> +@if(Auth::user()->is_deactivated)
Shouldn't this be `!Auth::user()->is_deactivated`?

2022-05-15 17:28 UTC, itinerare commented on resources/views/account/deactivated.blade.php
> +<p>Your account has been deactivate as of {!! format_date(Auth::user()->settings->deactivated_at) !!}. {{ Auth::user()->settings->deactivate_reason ? 'The following reason was given:' : '' }}</p>
Typo-- deactivate_d_

2022-05-15 17:28 UTC, itinerare commented on resources/views/pages/credits.blade.php
> +        <strong>Auto-populate New Image Traits</strong> by <a href="https://github.com/itinerare">itinerare</a> ({{ Config::get('lorekeeper.extensions.autopopulate_image_features') ? 'Enabled' : 'Dis
I'd rather at minimum that the toggleable exts remain at the end for clarity!

2022-05-18 16:41 UTC, preimpression commented on app/Http/Controllers/Users/AccountController.php
> +            flash('You have successfully successfully.')->success();
omfg

2022-05-18 17:01 UTC, itinerare commented on app/Http/Controllers/Users/AccountController.php
> +            flash('You have successfully successfully.')->success();
it's a mood tbh

2022-05-28 19:02 UTC, preimpression commented on app/Services/UserService.php
> +                    $galleryManager->postStaffComments($submission->id, ['staff_comments' => 'User\'s account was deactivated.'], ($staff ? $staff : $user));
What do I do about this, then?  It's basically the same code as used in user ban currently.

2022-05-28 19:06 UTC, itinerare commented on app/Services/UserService.php
> +                    $galleryManager->postStaffComments($submission->id, ['staff_comments' => 'User\'s account was deactivated.'], ($staff ? $staff : $user));
Might as well just leave it for the moment.... I can deal w cleaning it up later since it's functionally my problem

2022-05-28 19:07 UTC, preimpression commented
Not sure what to do about the format_php workflow since I am currently unable to push that file to my github. Gonna try to redo all my auth stuff to get it to work and allow it

2022-05-28 19:08 UTC, itinerare commented
I'm not sure what's to be done about it since it seems to be a sourcetree issue.... it's annoying, though. Since it perceives it as a conflict I can probably override it for this PR however

2022-05-28 19:09 UTC, itinerare approved these changes

2022-05-28 19:10 UTC, preimpression commented
What's odd is it's not just sourcetree, if I try to push via VSC itself it gives the same issue, so evidently it's my account. 
Also, about to pull the current develop into this branch too.

2022-05-28 19:12 UTC, itinerare commented
Weird. I've just handled it for the moment, so you can handle it being uncooperative on your own time

2022-06-14 09:20 UTC, Draginraptor approved these changes

2022-06-14 14:16 UTC, merged