Prompt permalinks
corowne/lorekeeper pull request #341
Opened 2022-07-13 18:02 UTC by AW0005

I've got this as an extension right now:
http://wiki.lorekeeper.me/index.php?title=Extensions:Prompt_Permalink

But it was mentioned in discord that this would be a good candidate for including in core.

2022-07-13 18:39 UTC, itinerare requested changes
Code broadly looks good too, just needs some minor adjustments!

2022-07-13 18:39 UTC, itinerare commented on app/Http/Controllers/PromptsController.php
> +        $prompt = Prompt::where('id', $id)->get()->first();
Probably add a `if(!$prompt) abort(404);` or somesuch as a fallback/to prevent errors

2022-07-13 18:39 UTC, itinerare commented on resources/views/prompts/prompt.blade.php
> +@section('title') All Prompts @endsection
Maybe adjust this to be something like "Prompts :: (prompt title)"?

2022-07-13 18:39 UTC, itinerare commented on resources/views/prompts/prompt.blade.php
> +    {!! breadcrumbs(['Prompts' => 'prompts', 'All Prompts' => 'prompts/prompts']) !!}
Should probably add the prompt title and relative address to the breadcrumbs!

2022-07-13 18:47 UTC, AW0005 commented
@itinerare Changes should be up!

2022-07-13 18:51 UTC, itinerare approved these changes

2022-07-19 00:19 UTC, SpeedyD approved these changes
Figured I'd give it a do-over as well. Code looks good and clean.

Only question I had is why the change from `<h4>` to `<h3>` for the Details and Rewards, but that's kind of a minor non-issue.

2022-07-19 00:37 UTC, AW0005 commented
@SpeedyD I think I nudged all the headers up by one from what is was before to fit better in the full page format.

2022-07-19 00:39 UTC, SpeedyD commented
> @SpeedyD I think I nudged all the headers up by one from what is was before to fit better in the full page format.

Fair enough! I'm honestly not sure if I'll even change it back myself.. I tried it out with my browser inspector and frankly, it doesn't look that bad either. Just made me go :thinking: basically. :+1:

2022-07-19 00:55 UTC, merged