Feature/auth rework
corowne/lorekeeper pull request #44
Opened 2020-11-17 22:12 UTC by itinerare

- Rework alias storage; move to new table
- Change verification checking and alias setting to fit new storage method
- Rework user alias checking/display for new storage method
- Add additional information to sites config for construction of links, etc
- Add auth and primary_alias toggles to sites config-- controlling whether it should be offered as an auth provider and whether aliases from the site can be a user's primary alias
- Build out a single alias info migration command; has an additional option, `--drop-columns`, which drops the alias columns when it is finished moving information either to user_id or url columns. It's recommended to run it without once and ensure data has been moved properly before running it again with the option.
- Update character ownership to use URL instead of alias
- Update character owner display to use prettyProfileLink function/handle a variety of sites
- Update character logs to use URL
- Add helper function to check if a URL is from a site used for auth, and if so, if it corresponds to an on-site user
- Add helper function to format 'name'@'link' string without link
- Tidy up art/design credit entry

2020-11-21 13:12 UTC, corowne requested changes
Looks good, just a few things:
- Admin panel (editing a user) - in the clear alias section, the alias textbox still uses the old alias as its value so the box is blank
- Admin\Users\UserController.php - related to the above; postUserAlias (to clear the old alias) needs to be updated to use the new alias table too
- BrowseController.php - masterlist character/MYO/sublist search by username still searches on owner_alias, user search by alias still searches on alias column on users

(Also not sure if within scope of this update - items still use artist_alias)

2020-11-21 13:12 UTC, corowne commented on app/Helpers/Helpers.php
> +        if($alias) $recipient = App\Models\User\User::find($alias->user_id);
You can use `$recipient = $alias->user;`, though I don't think it makes a major difference

2020-11-21 13:44 UTC, itinerare commented on app/Helpers/Helpers.php
> +        if($alias) $recipient = App\Models\User\User::find($alias->user_id);
Ahh yes
I don't think it does make much of a diff, but it feels tidier, so I like it, haha

2020-11-25 20:34 UTC, itinerare commented
All requested changes made-- I updated item artists to the new system as well. Going to take a look at addressing #49 before requesting review again though.

2020-11-28 13:34 UTC, corowne requested changes
Looks good I think, just one last thing!

2020-11-28 13:34 UTC, corowne commented on app/Http/Controllers/Admin/Users/UserController.php
>              UserUpdateLog::create(['staff_id' => Auth::user()->id, 'user_id' => $user->id, 'data' => json_encode($logData), 'type' => 'Clear Alias']);
I think this'll need a check to see if the alias is the primary alias/the only alias the user has and edit has_alias if the user has no other valid identification

2020-11-28 16:33 UTC, itinerare commented on app/Http/Controllers/Admin/Users/UserController.php
>              UserUpdateLog::create(['staff_id' => Auth::user()->id, 'user_id' => $user->id, 'data' => json_encode($logData), 'type' => 'Clear Alias']);
Oh yes! Thanks, I'll add that

2020-11-29 08:01 UTC, corowne approved these changes
Good to go I think!

2020-11-29 13:08 UTC, merged