feat(species): add visibility toggle
corowne/lorekeeper pull request #475
Opened 2022-12-22 21:50 UTC by SpeedyD

Adds a visible toggle for Species.
Will hide the species in the encyclopedia, search function of the masterlist/sublist/myo list and design update.

2022-12-22 22:18 UTC, itinerare requested changes

2022-12-22 22:18 UTC, itinerare commented on app/Http/Controllers/WorldController.php
> +            'subtypes' => $query->with('species')->visible()->orderBy('sort', 'DESC')->paginate(20)->appends($request->query()),
This needs to be a separate scope on the subtype model, probably checking the visibility of the parent species at minimum...

2022-12-22 23:05 UTC, SpeedyD commented on app/Http/Controllers/WorldController.php
> +            'subtypes' => $query->with('species')->visible()->orderBy('sort', 'DESC')->paginate(20)->appends($request->query()),
You are absolutely right- for now I'm removing this and will put it on my to-do list for a future 'subtype-visibility' feature.
Until then, administration just needs to be careful not to add subtypes to species they have hidden..

2022-12-22 23:05 UTC, itinerare approved these changes

2022-12-22 23:26 UTC, SpeedyD commented
**DO NOT APPROVE!** Found critical bug.

2022-12-23 01:04 UTC, itinerare approved these changes

2023-01-02 14:15 UTC, Draginraptor approved these changes

2023-01-02 14:21 UTC, merged