Feat: add usage of gravatar for user avatars
corowne/lorekeeper pull request #495
Opened 2023-01-13 11:56 UTC by Ne-wt

2023-01-13 13:32 UTC, itinerare approved these changes

2023-01-14 04:24 UTC, Draginraptor approved these changes

2023-01-14 04:45 UTC, SpeedyD requested changes
Looks fine except for the jpeg vs jpg file extension..

2023-01-14 04:45 UTC, SpeedyD commented on app/Models/User/User.php
> +                return url('assets/images/avatars/default.jpeg');
...Isn't this a problem? Filename is `default.jpeg`, while the default file is `default.jpg`.

2023-01-14 07:17 UTC, Draginraptor commented on app/Models/User/User.php
> +                return url('assets/images/avatars/default.jpeg');
I wanted to look into this more, and also realised that there's also `return $url;` on line 348, which means the if-else wouldn't be reached.

That said, `url('assets/images/avatars/default.jpeg')` should also be `url('images/avatars/default.jpg')` (inclusive of the jpeg to jpg change.

2023-01-14 07:19 UTC, Draginraptor requested changes
Check over the comments on the User model's getAvatarUrlAttribute function

2023-05-30 19:49 UTC, itinerare approved these changes

2023-06-04 04:35 UTC, AW0005 approved these changes

2023-06-04 11:54 UTC, merged