Feature/galleries
corowne/lorekeeper pull request #55
Opened 2020-12-04 20:49 UTC by itinerare

Merge [galleries](http://wiki.lorekeeper.me/index.php?title=Extensions:Galleries). Includes some changes relative to the current state of the extension:

New:
- Galleries can have set open/close times and can be hidden before start, much like prompts.
- Empty galleries with child/sub-galleries check if any visible submissions to their sub-galleries exist, and display the most recent. (Thanks to @preimpression for the idea!)
- Gallery submissions no longer have the option to select an associated prompt; instead, a list of associated prompt submissions (those where the url is the gallery submission's url) is gathered and the prompt details collected from those. This is used both to supply information for auto-prefixing as well as to populate a new section of gallery submission information containing a list of visible prompt submissions.

Misc:
- Removed package dependency

Bugs Fixed:
- Attempting to approve a submission with a character attached without an on-site owner causes approval to fail

Tested locally - Requires migrate, composer update (for those with galleries installed previously)

2020-12-05 11:26 UTC, corowne commented on app/Http/Controllers/Admin/Data/GalleryController.php
> +     * Sorts rarities.
Comment needs to be updated

2020-12-05 13:13 UTC, corowne requested changes
Mostly small comment edits and etc.; the two relatively larger ones are:
- Put the gallery settings in AddSiteSettings
- Shuffle some HTML out of a model

2020-12-05 13:13 UTC, corowne commented on .gitignore
> +clear_characters.sql
These aren't supposed to be here (also where does .idea come from?)

2020-12-05 13:13 UTC, corowne commented on app/Console/Commands/AddGallerySettings.php
> +<?php
I think the settings in this file should be combined with AddSiteSettings.php since it's being merged in

2020-12-05 16:52 UTC, itinerare commented on config/laravel-form-builder.php
> +<?php
Yes!

2020-12-05 16:56 UTC, itinerare commented on .gitignore
> +clear_characters.sql
They've mostly just accumulated as a result of successive folk adding things, so I'm not entirely sure where some of them come from-- I've removed them

2020-12-05 16:57 UTC, itinerare commented on app/Console/Commands/AddGallerySettings.php
> +<?php
Yeah that makes sense to me

2020-12-06 10:05 UTC, corowne requested changes
Mentioned 2 of these things on Discord, aside from that one small typo

2020-12-06 10:05 UTC, corowne commented on resources/views/galleries/index.blade.php
> +$sideGallery = null ?>
To put in the controller, as mentioned

2020-12-06 10:05 UTC, corowne commented on resources/views/galleries/_sidebar.blade.php
> +        ?>
To put in controller, as mentioned

2020-12-06 10:05 UTC, corowne commented on resources/views/galleries/_sidebar.blade.php
> +            <div class="sidebar-item"><a href="{{ url('user/'.Auth::user()->name.'/favorites') }}" class="{{ set_active('user/'.Auth::user()->name.'/favorits') }}">My Favorites</a></div>
Line 9, that is

2020-12-06 10:18 UTC, corowne approved these changes
Good to go I think!

2020-12-06 10:21 UTC, merged