Develop Issues fix PR
corowne/lorekeeper pull request #68
Opened 2021-01-19 13:28 UTC by Ne-wt

Fixed majority of issues (did not fix / attempt to fix issue #38)

All fixes where tested locally, logged in and out for those that could be affected by auth

2021-01-19 15:22 UTC, preimpression requested changes
A handful of suggestions. I only tested one thing, but I've seen the query->visible() bit used previously in something I believe Mercury did

2021-01-19 15:22 UTC, preimpression commented on app/Http/Controllers/Users/UserController.php
Might I suggest instead of an entire new variable, doing something like `if(!Auth::check() || !(Auth::check() && Auth::user()->hasPower('manage_characters')) $query->visible();` ?

2021-01-19 15:22 UTC, preimpression commented on composer.json
> +        "doctrine/dbal": "2.2",
October 15 commit by Merc suggests `"doctrine/dbal": "2.10.4",` and I believe it worked well on that for awhile.

2021-01-19 15:22 UTC, preimpression commented on resources/views/user/characters.blade.php
> +@if(Auth::check() && Auth::user()->hasPower('manage_characters'))
If you take my suggestion, don't forget to revert this back or let it work with the singular $characters variable!

2021-01-19 15:22 UTC, preimpression commented on resources/views/user/profile.blade.php
>      @endif
The $user->character() etc code might work as a Controller-set variable with the addition of my query suggestion from above, to reduce redundancy?

2021-01-19 15:22 UTC, preimpression commented on app/Services/ShopService.php
> +                    if($data['cost'][$key] < 0) throw new \Exception("One or more of the items is missing a cost.");
Tested, throws a SQL error. Try: ` == null` instead of `< 0`

2021-01-19 16:13 UTC, preimpression commented
Looking good so far! I'd suggest also handling Sublists and MYOs the same way!
Also, the masterlist might need the same functionality added

2021-01-23 03:22 UTC, itinerare commented on composer.json
> +        "doctrine/dbal": "2.2",
This was due to v2.11+ of the package requiring php 7.3 when at the time 7.2 was recommended for LK
As for the specific issue with migrations... what's been happening? I've not been having issues with it and I've been doing a ton of stuff with migrations w/ the existing version settings

2021-01-23 03:26 UTC, itinerare reviewed
Most of this looks good! Mostly curious about doctrine/dbal and if you plan to follow Uri's suggestion re ML/sublists/MYOs?

2021-01-23 04:18 UTC, preimpression commented on composer.json
> +        "doctrine/dbal": "2.2",
This was reported in the discord and reverting fixed the issue:
[Discord Link](https://discord.com/channels/678909186683437056/678909804940623893/794637552320774185)

I linked this stackoverflow related to their error: https://stackoverflow.com/questions/33817983/artisan-migration-error-class-doctrine-dbal-driver-pdomysql-driver-not-fo

I also recall having to do the same since I got the same error they were facing at one point and a revert fixed it.

2021-01-23 04:44 UTC, Draginraptor commented on composer.json
> +        "doctrine/dbal": "2.2",
To add on, I usually noticed it erroring when '->change()' is used (for editing existing columns)

2021-01-23 04:56 UTC, itinerare commented on composer.json
> +        "doctrine/dbal": "2.2",
Ahh, ok, that makes sense-- I only half-remembered the issue as reported, so ty! I also have not in fact been editing existing columns in that way so that tracks

2021-01-25 18:08 UTC, Ne-wt commented
added to myos/sublists and also added a missing use Settings to gallery collaborator model that caused a 500 error when trying to comment

2021-01-25 18:30 UTC, itinerare approved these changes

2021-01-30 09:25 UTC, Draginraptor approved these changes

2021-01-30 17:22 UTC, merged