Misc Bugfixes
corowne/lorekeeper pull request #735
Opened 2023-12-06 01:18 UTC by Ne-wt

contains a series of bug fixes and some QoL changes

issues mentioned in commits

2023-12-07 15:34 UTC, itinerare requested changes
It looks like there are a few small tweaks need making, but broadly, looks good! Thanks again for taking the time to do this, too.

2023-12-07 15:36 UTC, Ne-wt commented on app/Models/User/User.php
> +        return $this->hasMany('App\Models\Comment\CommentLike;');
oh just an oversight

2023-12-07 15:37 UTC, Ne-wt commented on resources/views/sales/_sales.blade.php
>      @if ((isset($sales->comments_open_at) && $sales->comments_open_at < Carbon\Carbon::now()) || (Auth::check() && Auth::user()->hasPower('edit_pages')) || !isset($sales->comments_open_at))
yes actually haha i missed it in here

2023-12-07 15:38 UTC, itinerare commented on resources/views/sales/_sales.blade.php
>      @if ((isset($sales->comments_open_at) && $sales->comments_open_at < Carbon\Carbon::now()) || (Auth::check() && Auth::user()->hasPower('edit_pages')) || !isset($sales->comments_open_at))
Yeah I only caught it because I went out of my way to scan for places where the relevant powers are used...

2023-12-07 16:13 UTC, Ne-wt commented on app/Models/Comment/Comment.php
> +namespace App\Models\Comment;
100%

2023-12-08 16:47 UTC, preimpression approved these changes
Looks good. Commented on a couple little things that probably wouldn't do anything but make me happy lol

2023-12-08 16:47 UTC, preimpression commented on app/Services/UserService.php
carbon -> Carbon ? Does this ever argue the same way auth instead of Auth does?

2023-12-08 16:47 UTC, preimpression commented on resources/views/admin/sales/create_edit_sales.blade.php
Weird formatting of count( etc, is it lint being silly?

2023-12-08 16:47 UTC, preimpression commented on resources/views/admin/submissions/submission.blade.php
Same weird formatting here

2023-12-08 16:47 UTC, preimpression commented on resources/views/home/_submission_content.blade.php
> +                $submission->characters()->whereRelation('character', 'deleted_at', null)->get()) != count($submission->characters()->get()))
Another lint weirdness

2023-12-09 11:44 UTC, Ne-wt commented on app/Services/UserService.php
it doesn't but I'll update for consistency, the other formatting issues unfortunately are lint and I can't do much about (line length)

2023-12-09 12:14 UTC, itinerare commented on app/Services/UserService.php
Yeah the blade formatter is just Like That.

2023-12-10 16:35 UTC, merged