Feature/wysiwyg comments
corowne/lorekeeper pull request #741
Opened 2023-12-11 19:35 UTC by Ne-wt

2023-12-11 19:46 UTC, itinerare requested changes
Looks good, though I'd like to see it bolted down a little more to be safe.

2023-12-11 19:46 UTC, itinerare commented on app/Http/Controllers/Comments/CommentController.php
> +        $comment->comment = config('lorekeeper.settings.wysiwyg_comments') ? $request->message : parse($request->message);
This needs to be run through HTML purifier if WYSIWYG I think (with any needed changes to edit logging as well).

2023-12-11 20:11 UTC, Ne-wt commented on app/Http/Controllers/Comments/CommentController.php
> +        $comment->comment = config('lorekeeper.settings.wysiwyg_comments') ? $request->message : parse($request->message);
parse is the purifier

2023-12-11 20:11 UTC, Ne-wt commented on app/Http/Controllers/Comments/CommentController.php
> +        $comment->comment = config('lorekeeper.settings.wysiwyg_comments') ? $request->message : parse($request->message);
also edit logging has been updated already

2023-12-11 20:19 UTC, itinerare approved these changes

2023-12-14 23:21 UTC, AW0005 approved these changes

2023-12-14 23:28 UTC, merged