add optional gallery submissions on prompts
corowne/lorekeeper pull request #847
Opened 2024-02-22 00:24 UTC by Ne-wt

2024-02-22 00:46 UTC, itinerare requested changes
Broadly looks good!

2024-02-22 00:46 UTC, itinerare commented on app/Http/Controllers/Users/SubmissionController.php
> +            $gallerySubmissions = GallerySubmission::where('user_id', Auth::user()->id)->where('status', 'Accepted')->orderBy('id', 'DESC')->get()->pluck('title', 'id');
Would be worth including submissions on which the user collaborated as well.

2024-02-22 00:46 UTC, itinerare commented on app/Models/Submission/Submission.php
> +        'url' => 'nullable',
The `url` validation rule was added as part of a way to harden that field... is there a reason it's removed?

2024-02-22 14:21 UTC, SpeedyD approved these changes
Approved on the condition @itinerare's comments are taken into consideration. :)

2024-02-22 23:12 UTC, Ne-wt commented on app/Models/Submission/Submission.php
> +        'url' => 'nullable',
in order for it to be used as a `title` field if needs be, but I can always just add it back!

2024-02-22 23:12 UTC, Ne-wt commented on app/Http/Controllers/Users/SubmissionController.php
> +            $gallerySubmissions = GallerySubmission::where('user_id', Auth::user()->id)->where('status', 'Accepted')->orderBy('id', 'DESC')->get()->pluck('title', 'id');
true!

2024-02-22 23:24 UTC, itinerare commented on app/Models/Submission/Submission.php
> +        'url' => 'nullable',
Hmm. I think it'd probably be safest to add it back, though open to other solutions that achieve the desired functionality *and* safety.

2024-02-27 19:00 UTC, itinerare requested changes

2024-03-02 19:16 UTC, itinerare approved these changes

2024-03-02 19:16 UTC, merged