Merge branch 'extension/multiple-subtypes' into release/v3.0.0
corowne/lorekeeper pull request #870
Opened 2024-03-06 12:40 UTC by Ne-wt

2024-03-06 12:40 UTC, Ne-wt commented
updated version that can be merged, didnt want to pull 3.0.0 on top of multiple subtypes so did the reverse for convenience

2024-03-06 12:42 UTC, itinerare commented
Gotcha. It should go into develop still but that's about the same, dependency updates aside, really,

2024-03-06 13:04 UTC, Ne-wt commented
i did mean to put it in develop haha, half paying attention since at work™

2024-03-06 13:10 UTC, itinerare commented
All good, no worries!

2024-03-06 13:21 UTC, SpeedyD reviewed
Other than the removal of two visible()s and the inclusion of composer.lock, I see no problems. If I could have an answer or a fix, I'd gladly approve.

2024-03-06 13:21 UTC, SpeedyD commented on app/Http/Controllers/Characters/DesignController.php
>              'rarities'  => ['0' => 'Select Rarity'] + Rarity::orderBy('sort', 'DESC')->pluck('name', 'id')->toArray(),
Is there a specific reason I'm missing why visible() is removed??

2024-03-06 13:21 UTC, SpeedyD commented on app/Http/Controllers/Characters/DesignController.php
>              'subtype'  => $id,
Here as well, visible() is removed..?

2024-03-06 13:21 UTC, SpeedyD commented on composer.lock
Should composer.lock not be excluded? It does not seem like there's a relevant change here.

2024-03-06 13:45 UTC, Ne-wt commented on app/Http/Controllers/Characters/DesignController.php
>              'rarities'  => ['0' => 'Select Rarity'] + Rarity::orderBy('sort', 'DESC')->pluck('name', 'id')->toArray(),
nah i just didnt even realise tbh haha

2024-03-06 13:46 UTC, Ne-wt commented on composer.lock
thats just from running composer update, i don't think its any harm to update packages etc but I don't mind just reverting it, only reason why was cause there was a conflict!

2024-03-06 13:53 UTC, itinerare commented on composer.lock
Since it's going into develop I don't mind much either way...

2024-03-06 16:39 UTC, SpeedyD commented on composer.lock
Fair enough. I'll drop this matter, then.

2024-03-06 16:40 UTC, SpeedyD approved these changes
You've fixed the issues I've pointed out, so I see no problem. Let's get this one into dev, folks~!

Say @Ne-wt.. Shop-features next?

2024-03-07 12:54 UTC, Ne-wt commented
> Say @Ne-wt.. Shop-features next?
probably not for a bit haha if I can pull myself together to wip up the updates I've been _intending_ then I wouldn't mind, but yeah forever debating between <this will be feature frozen if I merge> dilemma

2024-03-08 17:35 UTC, itinerare requested changes
Broadly looks good, just noticed a few things.
Thanks for taking the time to get this in order!

2024-03-08 17:35 UTC, itinerare commented on app/Console/Commands/ConvertCharacterSubtype.php
> +            Schema::create('character_image_subtypes', function (Blueprint $table) {
Is there a reason this initial table creation and the design updates column changes aren't done in a migration?

2024-03-08 17:35 UTC, itinerare commented on app/Http/Controllers/BrowseController.php
> +            'subtypes'    => ['any' => 'Any Subtype', 'hybrid' => 'Multiple / Hybrid Subtypes'] + Subtype::visible(Auth::check() ? Auth::user() : null)->orderBy('subtypes.sort', 'DESC')->pluck('name'
This is a neat addition!

2024-03-08 17:35 UTC, itinerare commented on app/Models/Character/CharacterDesignUpdate.php
> +        return isset($this->subtype_ids) ? json_decode($this->subtype_ids, true) : [];
Would it be easier to add the subtype IDs column as an array cast? Since that would handle JSON encode/decode.

2024-03-08 17:35 UTC, itinerare commented on app/Services/CharacterManager.php
> +            if($data['subtype_ids'])
Does this need `isset()`?

2024-03-08 17:35 UTC, itinerare commented on config/lorekeeper/extensions.php
> +    'multiple_subtype_limit' => 10, // The maximum number of subtypes a character can have. (frontend validation)
I'd still like to see backend validation for this as well.

2024-03-08 18:18 UTC, Ne-wt commented on app/Console/Commands/ConvertCharacterSubtype.php
> +            Schema::create('character_image_subtypes', function (Blueprint $table) {
because it needs to migrate the subtypes at the same time to the alt table

2024-03-08 18:19 UTC, Ne-wt commented on app/Services/CharacterManager.php
> +            if($data['subtype_ids'])
shouldnt do because the createImage sets array key to null

2024-03-08 18:32 UTC, itinerare commented on app/Console/Commands/ConvertCharacterSubtype.php
> +            Schema::create('character_image_subtypes', function (Blueprint $table) {
Gotcha. Fair enough

2024-03-08 18:33 UTC, itinerare commented on app/Services/CharacterManager.php
> +            if($data['subtype_ids'])
Ok, cool, just wanted to double-check.

2024-06-21 14:58 UTC, Ne-wt commented
note to self: update subtypes search attribute

2024-06-21 15:15 UTC, itinerare commented on config/lorekeeper/extensions.php
> +    'multiple_subtype_limit' => 10, // The maximum number of subtypes a character can have. (frontend validation)
Just need to remove the note re frontend validation, now!

2024-06-21 15:16 UTC, itinerare approved these changes

2024-06-22 02:08 UTC, SpeedyD commented
> note to self: update subtypes search attribute

@Ne-wt, does this mean you're not done with the PR? I'm willing to approve it right here and now, but the wording makes me think you got some last changes planned...

2024-08-27 20:15 UTC, ScuffedNewt commented
@SpeedyD @itinerare this pr should be ready

2024-08-27 20:36 UTC, SpeedyD approved these changes

2024-08-27 22:10 UTC, itinerare commented on README.md
> +$ php artisan convert-character-subtype
I'm dissatisfied with this being necessary as part of setup (vs table creation/modifications/etc being handled in a migration and the command only being necessary for data conversion/migration). Is there a practical way to achieve that?

2024-08-28 00:38 UTC, preimpression commented on README.md
> +$ php artisan convert-character-subtype
Laravel has a function to check if a table/column exists, perhaps we have a proper migration file that includes the changes under that if statement to that new setups don't have to dig through and find a bunch of commands to run

2024-08-28 10:36 UTC, ScuffedNewt commented on README.md
> +$ php artisan convert-character-subtype
I've added a migration file for this

2024-08-28 12:21 UTC, SpeedyD approved these changes
I __also__ approve of these new changes. ;P

2024-08-28 12:56 UTC, itinerare commented on README.md
> +$ php artisan convert-character-subtype
Thank you!

2024-08-28 13:07 UTC, itinerare commented on database/migrations/2024_08_28_103434_convert_character_subtypes.php
> +            $this->call('convert-character-subtype');
Very creative... again, is there something specific blocking putting the basic table creation/modification here as usual (barring dropping old columns after migrating data, which I agree is reasonable to do in a command)?

2024-08-28 15:12 UTC, ScuffedNewt commented on database/migrations/2024_08_28_103434_convert_character_subtypes.php
> +            $this->call('convert-character-subtype');
Ideally, if this migration is reversed there is minimal data loss, but considering users may unknowingly reverse and lose subtype conversions / data (especially if the feature is utilised) it would be best to prevent, in my opinion, accidental reversal

2024-08-28 15:12 UTC, ScuffedNewt commented on database/migrations/2024_08_28_103434_convert_character_subtypes.php
> +            $this->call('convert-character-subtype');
i dont really have any strong opinions on it though, that being said

2024-08-28 18:22 UTC, ScuffedNewt commented on app/Console/Commands/ConvertCharacterSubtype.php
> +        if (!Schema::hasTable('character_image_subtypes')) {
this is intentional for people who installed the extension

2024-08-28 19:42 UTC, itinerare commented on app/Console/Commands/ConvertCharacterSubtype.php
> +        if (!Schema::hasTable('character_image_subtypes')) {
Will it not interfere with sites that _haven't_, but then update, migrate, and now have the table but still need existing data to be moved around?

2024-08-28 20:15 UTC, itinerare commented on app/Console/Commands/ConvertCharacterSubtype.php
> +        if (!Schema::hasTable('character_image_subtypes')) {
Ah, gotcha!
Smart to have that check on the migration, though... I hadn't thought of that end of it.

2024-08-28 20:16 UTC, itinerare approved these changes

2024-08-28 20:18 UTC, merged