Feature/image blocking
corowne/lorekeeper pull request #926
Opened 2024-04-26 07:24 UTC by CH3RVB

This is my first PR to here, so be nice to me /hj

This is my third (i think) crack at making something like this. Everything else was either too clunky or felt... annoying to use? So this is my final solution. LOL. 

Adds a modular image blocking system for users. Users can curate their own blocklist by blocking a specific model + ID. Blocked models + IDs have their image blurred out until they become unblocked again by the user. I say model + ID because right now it's an image only thing, but theoretically you could apply this in other ways? 

With a small dosage of Moif magic, it automatically applies to all mentions of the blocked image across the site, as long as they hotlink directly to the image URL. Very easy to use across exts, simply plug in the block widget, block an image, and go.

I'm unsure about some aspects, such as the route for the image blocking, as well as how many different world/other entries I should even put this thing on. Maybe the button is also too annoying to look at? Dunno. Either way, it's here :')

2024-04-26 11:26 UTC, itinerare commented on app/Helpers/Helpers.php
> +    } else {
Generally speaking, with returns, you don't need to encase the second in the if/else-- nothing beyond a  `return` is executed  to begin with, so you can simply have the first in the if, then the second freestanding.

2024-04-26 11:47 UTC, itinerare requested changes
A good stab at an arguably relatively complex task!

2024-04-26 11:47 UTC, itinerare commented on app/Models/ImageBlock.php
> +        'item_id', 'item_type', 'user_id'
Referring to non-specific objects as "items" when "item" is a concept already extant in the codebase is... very confusing.

2024-04-26 11:47 UTC, itinerare commented on resources/views/layouts/app.blade.php
> +                [src="{{ $image->item->imageUrl ? $image->item->imageUrl : ($image->item->currencyImageUrl ? $image->item->currencyImageUrl : ($image->item->avatarUrl ? $image->item->avatarUrl : ''))
This logic would be better done in an attribute on the image block model, I think. Would be a good use case for a switch statement, potentially.

2024-04-26 11:47 UTC, itinerare commented on resources/views/layouts/app.blade.php
> +    @if (Auth::check() && count(Auth::user()->blockedImages))
The count here should just be able to be `Auth::user()->blockedImages->count()`, since iirc what you get out of a relation is either directly or functionally a collection.

2024-04-26 11:47 UTC, itinerare commented on resources/views/widgets/_item_block.blade.php
> + {!! Form::submit(checkItemBlock($item, Auth::user()) ? 'Unblock' : 'Block', ['class' => 'btn btn-success btn-sm '.(isset($float) && $float ? 'float-right' : '')]) !!}
Probably this should be clearer about *what's* being blocked.

2024-04-26 11:47 UTC, itinerare commented on resources/views/widgets/_item_block.blade.php
> + <input type="hidden" name="item_type" value="{{ $model }}" />
While the risk is low in a project like this that's *already* open source, it's generally not the best idea to plunk stuff like model names out in the open; comments already went through this, so have a look [at the form for those](/corowne/lorekeeper/blob/develop/resources/views/comments/_form.blade.php), etc. for an idea as to what to do about it.

2024-04-26 11:47 UTC, itinerare commented on routes/lorekeeper/members.php
> +    Route::post('image-blocks/block/{id}', 'AccountController@postBlockUnblockImage');
If you go a similar route to comments (wrt the above), this'll probably need to be changed accordingly, but the general gist and placement of the route are fine.

2024-04-26 11:47 UTC, itinerare commented on app/Services/UserService.php
> +            $block = ImageBlock::where([
You could probably trim off a little work and express this as `$user->blockedImages->where([non-user-id-conditions etc etc])->first()` too!

2024-04-26 11:47 UTC, itinerare commented on app/Services/UserService.php
> +            $item = $model::find($id);
It might be worthwhile to double-check that the object exists just to be safe, since it's technically in the 'accepting semi-arbitrary input from users' zone.

2024-04-26 13:01 UTC, itinerare commented
Belatedly, also... it might seem counterintuitive, but it might be an idea to have a page (akin to bookmarks) with the current user's blocked images, as a ready point of reference.

2024-05-07 22:10 UTC, Ne-wt requested changes
mostly nits, agree with what mercury has said
apologies if comments are short - in work PR review mode

2024-05-07 22:10 UTC, Ne-wt commented on app/Helpers/Helpers.php
nit: run composer lint to stop these weird style changes

2024-05-07 22:10 UTC, Ne-wt commented on app/Helpers/Helpers.php
> +    } else {
+1, can even just 
`return $block ? true : false`

2024-05-07 22:10 UTC, Ne-wt commented on app/Http/Controllers/Users/AccountController.php
again with composer lint

2024-05-07 22:10 UTC, Ne-wt commented on app/Http/Controllers/Users/AccountController.php
> +
should this be blank? if yes, change it to `!$service...` and remove else block

2024-05-07 22:10 UTC, Ne-wt commented on app/Models/ImageBlock.php
> +        'item_id', 'item_type', 'user_id'
+1, recommend `block_object_id` or `image_id` `image_type` etc

2024-05-07 22:10 UTC, Ne-wt commented on app/Models/ImageBlock.php
> +namespace App\Models;
should this be in the user space, since it is user specific, and be `UserImageBlock`? imo I think it should be since there is no user agnostic rows

2024-05-07 22:10 UTC, Ne-wt commented on app/Services/UserService.php
+1 to lint

2024-05-07 22:10 UTC, Ne-wt commented on database/migrations/2024_04_25_052128_add_image_blocking.php
> +return new class extends Migration
this should be `class FileName extends Migration` to stop errors on older installs

2024-05-07 22:10 UTC, Ne-wt commented on resources/views/user/_profile_content.blade.php
> +            @endif
nit: indents

2024-05-07 22:10 UTC, Ne-wt commented on resources/views/user/_profile_content.blade.php
> +            @endif
double nit: item should not be the variable name

2024-05-07 22:10 UTC, Ne-wt commented on resources/views/widgets/_item_block.blade.php
> +     $model = get_class($item);
further on prior nit: `$item` is not the best variable name

2024-05-07 22:10 UTC, Ne-wt commented on resources/views/world/_currency_entry.blade.php
> +                @include('widgets._item_block', ['item' => $currency, 'float' => true])
float seems to be true in most places, consider it being default to true and explicitly pass it as false, but that's mostly preference

2024-05-07 22:29 UTC, Ne-wt commented
Also unrelated, I find this a little bit strange to include in the default LK install, considering things like toyhouse etc etc don't employ this on general images, and if a specific lorekeeper has such images on items etc that may need to be blocked its best installed individually, imo
@itinerare thoughts?

2024-05-08 00:07 UTC, itinerare commented
On some level, I agree... but users may need to block seemingly innocuous stuff in certain cases, so it's not necessarily sufficient to install it on a case-by-case basis/only where more common points of friction occur.

2024-05-08 03:05 UTC, itinerare commented
To some degree, I feel like if it's worth including in core at all then there's no sense in undercutting it by putting it behind a toggle... 

I think the other part of it is that TH has a different use case than we do, so it's not necessarily practical to make a direct comparison there; TH doesn't really have images that persistently exist around the site in the same way (items, etc.) to be an issue in the first place. Generally speaking, you have more leeway to simply not look at a character or image on there that causes issues, and iirc can block characters-- so it does have _some_ manner of comparable function, just that the context is different.
The more direct analogue would probably be pet sites-- and imo the fact that those generally don't have this kind of option isn't in their favor.

It's one of those things where it's the safer and more considerate thing to be proactive about it and spare folks unnecessary stress, even if it feels like "overkill" in a lot of cases/to include in core.

2024-05-08 07:51 UTC, Ne-wt commented
> The more direct analogue would probably be pet sites

definitely, hit the nail on the head! brain wasn't braining yday

> It's one of those things where it's the safer and more considerate thing to be proactive about it and spare folks unnecessary stress, even if it feels like "overkill" in a lot of cases/to include in core.

firmly in the camp of <this is probably not a feature conducive? to core> since most items etc should not be causing these issues ideally, especially when compared to Lorekeepers mainstream counterparts
That being said, I think this would be better placed as having `Characters` as default -- since when #876 is inevitably cleaned and finished, users may still find that they want to block a certain character even if does is not necessarily fall under a "warning needed" category. 
In fact, I think that would be a much more requested feature than items

TLDR; IMO, if this feature is to be added...

- Change the primary focus of the default configuration to be for characters
- A toggle, if not (since other use cases would need to be manually added by a developer)

2024-05-08 08:01 UTC, Ne-wt commented on app/Models/ImageBlock.php
> +    protected $table = 'image_blocks';
following up on my prior comment about user space too, ideally the table should be `user_image_blocks` in similar fashion

2024-05-08 08:17 UTC, itinerare commented
> definitely, hit the nail on the head! brain wasn't braining yday

Haha, all good, been there.

Anyhow, yeah, I'm inclined to agree that characters are the bigger/more probable use case, so I think it's sensible enough to aim this more firmly _at_ that use case-- with support for other things essentially as a side benefit (albeit one that I do still find in favor of, personally). I'd agree that most items, etc. _shouldn't_ cause issues/it's generally good to avoid making ones that are liable to, but I'd rather provide users the ability to address these things for themselves.

2024-05-08 08:28 UTC, itinerare commented on app/Helpers/Helpers.php
Probably I'm just going to switch it to running on push for all branches again so neither reviewers nor contributors need to think about it, since my clever idea wrt running on PRs only was stymied (fairly reasonably) by repo perms... It was worth a shot |D

2024-05-08 08:32 UTC, Ne-wt commented on app/Helpers/Helpers.php
👌 
> It was worth a shot |D

can't work out all the time!

2024-05-08 08:35 UTC, Ne-wt commented on app/Helpers/Helpers.php
> +    } else {
actually follow up on this i'd do

`function checkImageBlock($image, $user)
{
    return App\Models\ImageBlock::where([
        ['image_id', '=', $image->id],
        ['image_type', '=', get_class($image)],
        ['user_id', '=', $user->id],
    ])->exists();
}`

2024-05-08 08:35 UTC, itinerare commented on app/Helpers/Helpers.php
Did that while I was thinking about it-- so it _should_ now be as easy as just merging in latest develop. Hopefully.

2024-05-08 08:54 UTC, itinerare commented on app/Models/ImageBlock.php
> +namespace App\Models;
Good call yeah, inclined to agree

2024-05-08 08:56 UTC, itinerare commented on database/migrations/2024_04_25_052128_add_image_blocking.php
> +return new class extends Migration
_Does_ this cause issues? My understanding was that upstream (wrt Laravel) this change was following PHP supporting it, so it doesn't make much sense to me that (assuming PHP is upgraded, which needs to happen regardless) this should be a problem.

2024-05-08 08:59 UTC, itinerare commented on app/Models/ImageBlock.php
> +    protected $table = 'image_blocks';
Likewise, agree on this

2024-05-08 09:11 UTC, Ne-wt commented on database/migrations/2024_04_25_052128_add_image_blocking.php
> +return new class extends Migration
I've found on SOME sites it can be an issue, & quiet often on local (people on windows / older xampp)
perhaps in this case it *should* be fine since this is on v3 which should implicitly mean that the php version is up to par, so take this comment with a grain of salt

2024-05-08 09:18 UTC, itinerare commented on database/migrations/2024_04_25_052128_add_image_blocking.php
> +return new class extends Migration
I'm inclined to let this be since yeah, v3 explicitly requires PHP be reasonably up-to-date (whereas on current release it's supported but not technically _forced_)...

2025-01-12 14:13 UTC, CH3RVB commented
cancelling due to feedback

2025-01-12 14:13 UTC, closed without merging